WIP: Add Dockerfile, build pipeline, push to DockerHub
pacifica/pacifica-metadata-mgmt pull request #28
Opened 2019-09-10 21:09 UTC by GitBytes

### Description

Adds a Dockerfile and build pipeline to support container deployment.

### Issues Resolved

Fixes #27 
Fixes https://github.com/pacifica/pacifica/issues/22

### Check List

- [ ] All tests pass. See <https://github.com/pacifica/pacifica-docs/blob/master/development/TESTING.md>
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable

2019-09-11 20:52 UTC, GitBytes commented
@dmlb2000 I think this is ready for review now. Thanks.

2019-09-12 18:48 UTC, dmlb2000 requested changes
I would suggest moving the eslint dependencies back to devDependencies then it should be good to go.

2019-09-12 18:48 UTC, dmlb2000 commented on package.json
> +    "react-table": "^6.10.0",
All the eslint stuff shouldn't be in the dependencies, it's a dev dependency. Why were these moved here?

2019-09-12 18:51 UTC, GitBytes commented on package.json
> +    "react-table": "^6.10.0",
Production build was failing otherwise. Maybe I was mistaken? @dmlb2000

2019-09-12 19:39 UTC, dmlb2000 commented on package.json
> +    "react-table": "^6.10.0",
So as far as I can tell from a bit of searching...

 * https://github.com/facebook/create-react-app/issues/1764
 * https://github.com/facebook/create-react-app/issues/7078
 * https://stackoverflow.com/questions/54677395/error-failed-to-load-plugin-import-cannot-find-module-eslint-plugin-import-w
 * https://create-react-app.dev/docs/setting-up-your-editor#formatting-code-automatically
 * https://create-react-app.dev/docs/production-build

I've come to some conclusions:

  * Seems like the react community doesn't give a damn about trying to keep development dependencies away from production dependencies.
  * The build (`npm run build`) should produce a compiled build for production use.
  * The production build should compile out any code that isn't required directly by the App.
  * The dependencies should be viewed as a single blob just install them all and let the compiler figure it out (hopefully it will).

Makes sense?

2019-09-12 21:41 UTC, GitBytes commented on package.json
> +    "react-table": "^6.10.0",
That makes sense. I'll make sure there is no split between dev and prod deps then? I can make that change and submit that for approval as well.

2019-09-12 21:47 UTC, dmlb2000 commented on package.json
> +    "react-table": "^6.10.0",
That's the thought, just do an `npm install` and don't worry about getting a thousands of packages that are only useful when developing the application... *sigh*

2019-09-13 20:12 UTC, dmlb2000 commented on package.json
> +    "react-table": "^6.10.0",
Should be resolved with my changes.

2019-09-13 21:18 UTC, dmlb2000 approved these changes
I fixed the build the way I like it, should be fine now.

2019-09-13 21:18 UTC, merged

2019-09-13 21:25 UTC, GitBytes commented on Dockerfile
> +FROM node:10-stretch AS base
@dmlb2000 After doing some additional testing, we should ok to move to alpine based images as it will significantly reduce image size.